version: "3.7"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=America/New_York
    volumes:
      - /docker-cluster/jellyfin/config:/config
      - /docker-cluster/jellyfin/cache:/cache
      - type: bind
        source: /home/jellyfin/movies
        target: /media
      - type: bind
        source: /home/jellyfin/tv
        target: /media2
        read_only: true
    ports:
      - 8096:8096
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
